version: "3"

services:
  db:
    image: postgres:13-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bank_application
      POSTGRES_USER: bank_application_user
      POSTGRES_PASSWORD: bank_application_password
    ports:
      - "5432:5432"